/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tiendaapp.Vista;

import com.mycompany.tiendaapp.App;
import com.mycompany.tiendaapp.Carrito;
import com.mycompany.tiendaapp.Interfaces.FabricaMuebles;
import com.mycompany.tiendaapp.clases.FabricaKali;
import com.mycompany.tiendaapp.clases.FabricaLondon;
import com.mycompany.tiendaapp.clases.Producto;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ASUS
 */
public class Tecnologia extends javax.swing.JPanel {
    //private CarritoLista infoCarrito = new CarritoLista();
    //private CarritoLista carrito;
    //private DefaultListModel<Producto> carritoModel;
     
    public Tecnologia() {
        initComponents();
        MostrarImagenes();
        //carritoModel = new DefaultListModel<>();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        celular = new javax.swing.JLabel();
        scooter = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        televisor = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        smartWatch = new javax.swing.JLabel();
        laptop = new javax.swing.JLabel();
        camara = new javax.swing.JLabel();
        txtTelevisor = new javax.swing.JTextField();
        txtScooter = new javax.swing.JTextField();
        txtLaptop = new javax.swing.JTextField();
        txtCamara = new javax.swing.JTextField();
        txtSmartWatch = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Principal"); // NOI18N

        celular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celular.setText("licua");

        scooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scooter.setText("refri");

        jPanel1.setBackground(new java.awt.Color(21, 145, 155));

        jButton1.setText("London");

        jButton2.setText("Kali");

        jLabel3.setText("Juego de Muebles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        televisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        televisor.setText("aire");

        smartWatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smartWatch.setText("ventila");

        laptop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laptop.setText("Microo");

        camara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camara.setText("Aspirad");

        btnAgregar.setBackground(new java.awt.Color(9, 209, 199));
        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(12, 100, 120));
        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCarrito.setBackground(new java.awt.Color(21, 145, 155));
        btnCarrito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrito.setText("Carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnCarrito)
                        .addGap(37, 37, 37)
                        .addComponent(btnAgregar)
                        .addGap(41, 41, 41)
                        .addComponent(btnLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smartWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(txtSmartWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(laptop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(txtLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtScooter, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(scooter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(camara, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(televisor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCamara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(txtTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scooter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(televisor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smartWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camara, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSmartWatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCarrito))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void MostrarImagenes() {
        // Agregar un listener al panel para ajustar las imágenes cuando cambie el tamaño
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                
                setImageLabel(celular, "src/main/resources/Imagenes1/celular.jpg");
                setImageLabel(scooter, "src/main/resources/Imagenes1/scooter.jpg");
                setImageLabel(televisor, "src/main/resources/Imagenes1/televisor.jpg");
                setImageLabel(smartWatch, "src/main/resources/Imagenes1/smartwatch.jpg");
                setImageLabel(laptop, "src/main/resources/Imagenes1/laptop.jpg");
                setImageLabel(camara, "src/main/resources/Imagenes1/goPro.png");
            }
        });
    }
    private void setImageLabel(JLabel labelName, String root){
        SwingUtilities.invokeLater(() -> {
            ImageIcon imagen = new ImageIcon(root);
                if (labelName.getWidth() <= 0 || labelName.getHeight() <= 0) {
                    System.err.println("Error: Dimensiones del JLabel son inválidas (ancho o alto igual a 0).");
                    return;
                }
            Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_SMOOTH));
            labelName.setIcon(icon);
            this.repaint();
        });
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Producto p1 = new Producto.ProductoBuilder(1, "GoPro Camara", "Tecnologia", 600).build();
        Producto p2 = new Producto.ProductoBuilder(1, "Televisor 4k", "Tecnologia", 2500).build();
        Producto p3 = new Producto.ProductoBuilder(1, "Smart Watch", "Tecnologia", 2000).build();
        Producto p4 = new Producto.ProductoBuilder(1, "S24 Ultra", "Tecnologia", 4200).build();
        Producto p5 = new Producto.ProductoBuilder(1, "Asus Gamer", "Tecnologia", 3500).build();
        Producto p6 = new Producto.ProductoBuilder(1, "Scooter Electrica", "Tecnologia", 1800).build();
        
        String aux1 = txtCamara.getText();
        String aux2 = txtTelevisor.getText();
        String aux3 = txtSmartWatch.getText();
        String aux4 = txtCelular.getText();
        String aux5 = txtLaptop.getText();
        String aux6 = txtScooter.getText();
        
        if(aux1.isBlank()){aux1="0";txtCamara.setText("0");}
        if(aux2.isBlank()){aux2="0";txtTelevisor.setText("0");}
        if(aux3.isBlank()){aux3="0";txtSmartWatch.setText("0");}
        if(aux4.isBlank()){aux4="0";txtCelular.setText("0");}
        if(aux5.isBlank()){aux5="0";txtLaptop.setText("0");}
        if(aux6.isBlank()){aux6="0";txtScooter.setText("0");}
        
        if(aux1.matches("[0-9]+") && aux2.matches("[0-9]+")&& aux3.matches("[0-9]+")&& aux4.matches("[0-9]+")&& aux5.matches("[0-9]+")&& aux6.matches("[0-9]+")){
            int cantA = Integer.parseInt(txtCamara.getText());
            int cantB = Integer.parseInt(txtTelevisor.getText());
            int cantC = Integer.parseInt(txtSmartWatch.getText());
            int cantD = Integer.parseInt(txtCelular.getText());
            int cantE = Integer.parseInt(txtLaptop.getText());
            int cantF = Integer.parseInt(txtScooter.getText());
            
            for (int i = 0; i < cantA; i++) {App.lista.add(p1);}
            for (int i = 0; i < cantB; i++) {App.lista.add(p2);}
            for (int i = 0; i < cantC; i++) {App.lista.add(p3);}
            for (int i = 0; i < cantD; i++) {App.lista.add(p4);}
            for (int i = 0; i < cantE; i++) {App.lista.add(p5);}
            for (int i = 0; i < cantF; i++) {App.lista.add(p6);}
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un numero correcto");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        
        JFrame principal = (JFrame) SwingUtilities.getWindowAncestor(this);  // Obtener el JFrame contenedor
        principal.dispose();
        var aplicativo = new Carrito();
        aplicativo.setVisible(true);
        aplicativo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCarritoActionPerformed
    void limpiar(){
        txtCamara.setText("");
        txtSmartWatch.setText("");
        txtLaptop.setText("");
        txtCelular.setText("");
        txtScooter.setText("");
        txtTelevisor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel camara;
    private javax.swing.JLabel celular;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel laptop;
    private javax.swing.JLabel scooter;
    private javax.swing.JLabel smartWatch;
    private javax.swing.JLabel televisor;
    private javax.swing.JTextField txtCamara;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtLaptop;
    private javax.swing.JTextField txtScooter;
    private javax.swing.JTextField txtSmartWatch;
    private javax.swing.JTextField txtTelevisor;
    // End of variables declaration//GEN-END:variables
}
